(* CSCI 5535
 *
 * Based on code by Wes Weimer.
 *
 * This is a driver file for the homework 3 project. 
 *
 * Do not edit this file -- instead, edit hw3.ml and submit that as per the
 * directions in the homework. 
 *)
open Printf

exception Error

let main () = 
  let silent = ref false in 
  let trace = ref false in
  let args = [
    "--silent", Arg.Set silent, "do not display a prompt or reminder" ;
    "--trace", Arg.Set trace, "print a trace of evaluation"
  ] in 
  Arg.parse args (fun _ -> ()) "" ; 

  if not !silent then begin 
    printf "Enter an IMP command (use . to end your command):\n" ;
    flush stdout ; 
  end ; 
  let lexbuf = Lexing.from_channel stdin in
  let prog = Parse.exp Lex.initial lexbuf in
  if not !silent then begin 
    print_endline (Ast.exp_to_str prog) ; 
  end ;
  let result = Eval.isSimp prog in
  printf "%b\n" (result);
  exit 0 
;;
main () ;;
